#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

nix-shell $DIR/default.nix -A shells.ghc --add-root $DIR/dist-newstyle/gc-roots/gc-root --indirect --run "ghcid -c'ghci -O0 -DUSE_WARP -Wall -icommon/src -ifrontend/src Main' -W -T'Main.main'"
